spring:
  datasource:
    hikari:
      maximum-pool-size: 20
  application:
    name: pharmacie
  profiles:
    active: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 30
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pharmaventeerp@gmail.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080